Add helper for create credential offer
evannetwork/vade-evan pull request #34
Opened 2023-01-30 10:01 UTC by wulfraem

## DRAFT NOTE

- [ ] wait for #33 to be merged
- [ ] current helper logic is parked in `src/helpers/credential_merge_with_pr33_later_on.rs`, this should be moved into the credentials helper from #33
## Description

Adds helper for create credential offer to make API easier to use.

## Details

- had to bump dependencies of the `vade-didcomm` dependency tree to resolve version conflicts with `ssi` crate

2023-01-30 11:15 UTC, Tschuck commented on src/helpers/credential_merge_with_pr33_later_on.rs
> +        id: "uuid:834ca9da-9f09-4359-8264-c890de13cdc8".to_string(),
Do we need some random uuid here?

2023-01-30 11:15 UTC, Tschuck commented on src/helpers/credential_merge_with_pr33_later_on.rs
> +        issuance_date: "2021-01-01T00:00:00.000Z".to_string(),
Do we need today here?

2023-02-01 12:12 UTC, S3bb1 requested changes

2023-02-01 12:12 UTC, S3bb1 commented on Cargo.toml
> +branch = "feature/update-didcomm-rs-to-no-resolve-version"
merged now
```suggestion
git = "https://github.com/evannetwork/vade-didcomm.git"
branch = "develop"
```

2023-02-02 08:25 UTC, merged