Add verify credential helper
evannetwork/vade-evan pull request #37
Opened 2023-02-03 09:23 UTC by wulfraem

Adds helper to verify credentials to verify credentials in a convenient way.

## Details

- add helper
- add bindings for CLI, c-lib, wasm
- refactor helper & bindings align implementation style

2023-02-03 09:53 UTC, S3bb1 requested changes

2023-02-03 09:53 UTC, S3bb1 commented on src/helpers/credential.rs
> +        // verify the credential issuer
```suggestion
```

can this be removed?

2023-02-03 09:53 UTC, S3bb1 commented on src/main.rs
> +                    .about("Creates a `CredentialOffer` message. A `CredentialOffer` is sent by an issuer and is the response to a `CredentialProposal`. The `CredentialOffer` specifies which schema t
i think the `about` section is wrong :-D

2023-02-03 09:53 UTC, S3bb1 commented on src/main.rs
> +                    .arg(get_clap_argument("subject_did")?),
needs to be aligned as well 🍡

2023-02-03 09:53 UTC, S3bb1 commented on src/main.rs
> +            .takes_value(true),
can be removed, is unused then

2023-02-03 09:53 UTC, S3bb1 commented on src/main.rs
> +                        get_argument_value(sub_m, "verification_method_id", None),
unused

2023-02-03 09:53 UTC, S3bb1 commented
release notes not adjusted

2023-02-03 13:14 UTC, wulfraem commented on src/main.rs
> +                    .arg(get_clap_argument("subject_did")?),
+1 for the dango emoji 🍡 ^^

2023-02-03 13:42 UTC, S3bb1 approved these changes

2023-02-06 08:19 UTC, Tschuck approved these changes

2023-02-06 08:19 UTC, Tschuck commented on src/wasm_lib.rs
> +
```suggestion
```

2023-02-06 08:22 UTC, merged