Feature/remove credential subject
evannetwork/vade-evan pull request #57
Opened 2023-04-20 12:58 UTC by vineetpant

## Descripton

credential_subject.id  has been removed from vade-evan-bbs and vade-jwt-vc , the functions and payloads need to be updated to reflect the change.

## Details

- Add subject_id param to helper functions where subject_did is required
- Adjust payload to functions where subject_did is passed
- Adjust test cases
- Update c-lib, wasm, cli bindings

2023-04-27 13:02 UTC, Tschuck commented on src/api/vade_evan_api.rs
> +    ///         const SUBJECT_DID: &str = "did:evan:EiAee4ixDnSP0eWyp0YFV7Wt9yrZ3w841FNuv9NSLFSCVA";
```suggestion
    ///         const PROVER_DID: &str = "did:evan:EiAee4ixDnSP0eWyp0YFV7Wt9yrZ3w841FNuv9NSLFSCVA";
```

2023-04-27 13:02 UTC, Tschuck commented on src/api/vade_evan_api.rs
> +    ///                   SUBJECT_DID,
```suggestion
    ///                   PROVER_DID,
```

2023-04-27 13:02 UTC, Tschuck commented on src/helpers/credential.rs
>                  "email": "value@x.com"
Id is still there in line 1065.

`"id": "did:evan:EiAOD3RUcQrRXNZIR8BIEXuGvixcUj667_5fdeX-Sp3PpA",`

2023-04-27 13:02 UTC, Tschuck commented on src/helpers/presentation.rs
> +        "id": "did:evan:EiAee4ixDnSP0eWyp0YFV7Wt9yrZ3w841FNuv9NSLFSCVA",
```suggestion
```

2023-05-03 16:55 UTC, vineetpant commented
aligned vade_evan for new vade_bbs structures, @S3bb1  @wulfraem @Tschuck

2023-05-11 15:25 UTC, wulfraem requested changes

2023-05-11 15:25 UTC, wulfraem commented on Cargo.toml
> +branch = "feature/remove-credential-subject-id"
Just as a reminder before merging this MR too early: This should be updated after merging the [related MR](https://github.com/evannetwork/vade-jwt-vc/pull/7).

2023-05-11 15:25 UTC, wulfraem commented on Cargo.toml
> +branch = "feature/remove-credential-subject-id"
Just as a reminder before merging this MR too early: This should be updated after merging the [related MR](https://github.com/evannetwork/vade-evan-bbs/pull/31).

2023-05-11 15:25 UTC, wulfraem commented on src/helpers/credential.rs
> +    // }
Do we still need it? ^^

2023-05-11 15:25 UTC, wulfraem commented on src/helpers/presentation.rs
> +     }"###;
```suggestion
    }"###;
```

^^

2023-05-12 08:35 UTC, vineetpant commented on Cargo.toml
> +branch = "feature/remove-credential-subject-id"
yes, i am waiting for `credential_subject_id remove` branch to be merged so that it can be updated.

2023-05-12 08:37 UTC, vineetpant commented on Cargo.toml
> +branch = "feature/remove-credential-subject-id"
yes, i am waiting for credential_subject_id remove branch to be merged so that it can be updated.

2023-05-12 08:43 UTC, vineetpant commented on src/helpers/credential.rs
> +    // }
removed the unused commented code

2023-05-15 13:43 UTC, wulfraem approved these changes

2023-05-15 14:07 UTC, S3bb1 approved these changes

2023-05-15 14:07 UTC, merged