Add helper convert to nquads
evannetwork/vade-evan pull request #85
Opened 2023-09-13 10:37 UTC by vineetpant

## Description

This MR adds `helper_convert_credential_to_nquads` helper function to Credentials helper to provide support for nquads conversion to sdk functions

## Details

- Add `helper_convert_credential_to_nquads`
- Update bindings for c, wasm and cli
- Add test case for `helper_convert_credential_to_nquads`
- Update Versions.md

2023-09-14 08:01 UTC, wulfraem requested changes

2023-09-14 08:01 UTC, wulfraem commented on src/main.rs
>              #[cfg(all(feature = "vc-zkp-bbs", feature = "did-sidetree"))]
Do we need `did-sidetree` for the nquads? ^^

2023-09-14 08:01 UTC, wulfraem commented on src/api/vade_evan_api.rs
> +    /// Converts a given credential to nquads Vector
I think we should mention in the comments that we create canonized nquads as they're slightly more specific than normal nquads.

2023-09-14 08:46 UTC, vineetpant commented on src/main.rs
>              #[cfg(all(feature = "vc-zkp-bbs", feature = "did-sidetree"))]
not required , removed it from all bindings and cli now

2023-09-14 08:47 UTC, vineetpant commented on src/api/vade_evan_api.rs
> +    /// Converts a given credential to nquads Vector
updated comments

2023-09-18 05:39 UTC, wulfraem approved these changes

2023-09-18 06:12 UTC, S3bb1 approved these changes

2023-09-18 06:12 UTC, merged